public  class PrimitiveDataTypeDemo2 {
   public void print1(){
       ID id1 = '0018Z00002f8fG4QAI';
       system.debug('print id = '+ id1);

       //object --> object is a parent class to all primitive datatypes,sobjects, custom classes and everything in apex
       object obj1 = 'This is a string';
       object obj2 = 15;
       object obj3 = '0018Z00002f8fG4QAI';
       object obj4 = true;
       
       system.debug('obj1 = '+ obj1);
       system.debug('obj2 = '+ obj2);
       system.debug('obj3 = '+ obj3);
       system.debug('obj4 = '+ obj4);

    

       


       
       

   }

}
