Calculator c = new Calculator();
/*c.printNewMessage('This is new age calc.');
c.printNewMessage('this is new age calc. New one');

string message = 'this is new message to print';

c.printNewMessage(message);

c.add(5,7);
c.add(6,9);*/


/*string result = c.printAndReturnMessage('this is a parameter');
system.debug(result);*/

Calculator c = new Calculator();
integer sum1 = c.add(15,40);
system.debug('sum1 = ' + sum1);





